# Generated by Django 5.2.8 on 2025-11-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openrouterresponse',
            old_name='estimated_cost',
            new_name='estimated_completion_cost',
        ),
        migrations.AddField(
            model_name='openrouterresponse',
            name='estimated_image_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='openrouterresponse',
            name='estimated_prompt_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
