# Generated by Django 5.2.8 on 2025-11-27 04:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_message_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="model",
            new_name="model_id",
        ),
    ]
