# Generated by Django 5.2.8 on 2025-11-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_model_message_model_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="auto_generate_titles",
            field=models.BooleanField(
                default=False, help_text="Automatically generate conversation titles using AI"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="title_generation_frequency",
            field=models.PositiveIntegerField(
                default=4, help_text="Generate title every N messages (e.g., 4 = every 4th message)"
            ),
        ),
    ]
