# Generated by Django 5.2.8 on 2025-11-30 03:56

import uuid

import django.db.models.deletion
from django.db import migrations, models

import api.features.conversations.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_messageattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageattachment",
            name="file",
            field=models.FileField(
                upload_to=api.features.conversations.models.message_attachment_upload_to
            ),
        ),
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=api.features.conversations.models.generated_image_upload_to
                    ),
                ),
                ("prompt", models.TextField()),
                ("model_used", models.CharField(max_length=350)),
                ("aspect_ratio", models.CharField(blank=True, max_length=10, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_images",
                        to="api.message",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
