# Generated by Django 5.2.8 on 2025-12-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_messageattachment_file_generatedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="openrouterresponse",
            name="cost",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="openrouterresponse",
            name="image_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
