# Generated by Django 5.2.8 on 2025-12-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_openrouterresponse_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openrouterresponse",
            name="reasonng_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
