# Generated by Django 5.2.8 on 2025-12-06 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_openrouterresponse_reasonng_tokens"),
    ]

    operations = [
        migrations.RenameField(
            model_name="openrouterresponse",
            old_name="reasonng_tokens",
            new_name="reasoning_tokens",
        ),
    ]
