# Generated by Django 5.2.8 on 2025-12-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_rename_reasonng_tokens_openrouterresponse_reasoning_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="openrouterresponse",
            name="estimated_reasoning_cost",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
