# Generated by Django 5.2.8 on 2025-12-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_openrouterresponse_estimated_reasoning_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openrouterresponse",
            name="estimated_image_cost",
        ),
        migrations.AddField(
            model_name="openrouterresponse",
            name="upstream_inference_completions_cost",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="openrouterresponse",
            name="upstream_inference_cost",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="openrouterresponse",
            name="upstream_inference_prompt_cost",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
