# Generated by Django 5.2.8 on 2025-12-07 02:46

import api.features.conversations.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_remove_openrouterresponse_estimated_image_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reasoning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reasoning",
                        to="api.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedReasoningImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=api.features.conversations.models.reasoning_image_upload_to
                    ),
                ),
                ("model_used", models.CharField(max_length=350)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reasoning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reasoning_images",
                        to="api.reasoning",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
