# Generated by Django 5.2.8 on 2025-12-07 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_add_message_to_reasoning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reasoning",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reasoning",
                to="api.message",
            ),
        ),
    ]
