# Generated by Django 5.2.8 on 2025-12-14 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_reasoning_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useraddedmodel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="useraddedmodel",
            name="provider",
            field=models.CharField(
                choices=[("openrouter", "OpenRouter"), ("ollama", "Ollama")],
                default="openrouter",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useraddedmodel",
            unique_together={("user", "model_id", "provider")},
        ),
    ]
