# Generated by Django 5.2.8 on 2025-12-14 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_useraddedmodel_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("openrouter", "OpenRouter"), ("ollama", "Ollama")],
                        default="openrouter",
                        max_length=50,
                    ),
                ),
                ("raw_payload", models.JSONField()),
                ("request_id", models.CharField(db_index=True, max_length=255)),
                ("model_used", models.CharField(max_length=100)),
                ("finish_reason", models.CharField(blank=True, max_length=50, null=True)),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("completion_tokens", models.IntegerField(blank=True, null=True)),
                ("image_tokens", models.IntegerField(blank=True, null=True)),
                ("reasoning_tokens", models.IntegerField(blank=True, null=True)),
                ("total_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "estimated_prompt_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "estimated_completion_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "estimated_reasoning_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "upstream_inference_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "upstream_inference_prompt_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "upstream_inference_completions_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_response",
                        to="api.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="OpenRouterResponse",
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(
                fields=["-created_at", "model_used"], name="api_airespo_created_7d4362_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(fields=["provider"], name="api_airespo_provide_2494b9_idx"),
        ),
    ]
