# Generated by Django 5.2.8 on 2025-12-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_airesponse_delete_openrouterresponse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="default_provider",
            field=models.TextField(blank=True, null=True),
        ),
    ]
