# Generated by Django 5.2.8 on 2025-12-16 01:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_profile_default_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='A short, memorable name for the persona (e.g., "Sarcastic AI", "Helpful Assistant")',
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A brief description of what this persona is about."
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Detailed instructions for the LLM on how to behave as this persona."
                    ),
                ),
                (
                    "example_dialogue",
                    models.TextField(
                        blank=True,
                        help_text="Provide an example dialogue to guide the persona's style and responses.",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        blank=True,
                        help_text='Optional: The ID of a specific model to use with this persona (e.g., "ollama/llama3", "openrouter/anthropic/claude-3-haiku")',
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this persona can be viewed and used by other users.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this persona is currently active and selectable.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "unique_together": {("user", "name")},
            },
        ),
    ]
