# Generated by Django 5.2.8 on 2025-12-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_persona"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="provider",
            field=models.CharField(
                choices=[("openrouter", "OpenRouter"), ("ollama", "Ollama")],
                default="openrouter",
                max_length=20,
            ),
        ),
    ]
