# Generated by Django 5.2.8 on 2025-12-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_persona_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="persona",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
