# Generated by Django 5.2.8 on 2025-12-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_persona_deleted_persona_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="persona_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
