# Generated by Django 5.2.8 on 2025-12-16 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_message_persona_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="persona_id",
        ),
        migrations.AddField(
            model_name="message",
            name="persona",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persona",
                to="api.persona",
            ),
        ),
    ]
