# Generated by Django 5.2.8 on 2025-12-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_remove_message_persona_id_message_persona"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="persona_image",
            field=models.ImageField(blank=True, null=True, upload_to="persona_images/"),
        ),
    ]
