# Generated by Django 5.2.8 on 2025-12-16 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_persona_persona_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="api.persona",
            ),
        ),
    ]
