# Generated by Django 5.2.8 on 2025-12-16 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_alter_message_persona"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="persona",
            unique_together=set(),
        ),
    ]
