# Generated by Django 5.2.8 on 2025-12-17 00:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_alter_persona_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("flow_data", models.JSONField(default=dict)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FlowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "total_execution_time",
                    models.IntegerField(
                        blank=True, help_text="Total execution time in milliseconds", null=True
                    ),
                ),
                ("execution_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("failed_node_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="api.flow",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="FlowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conversation", "Conversation"),
                            ("analysis", "Analysis"),
                            ("generation", "Generation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                ("template_data", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=True)),
                ("times_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-times_used", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NodeExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("node_id", models.CharField(db_index=True, max_length=255)),
                ("node_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(blank=True, null=True)),
                ("output_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_code", models.CharField(blank=True, default="", max_length=100)),
                ("error_details", models.JSONField(blank=True, null=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_time",
                    models.IntegerField(
                        blank=True, help_text="Execution time in milliseconds", null=True
                    ),
                ),
                ("model_used", models.CharField(blank=True, default="", max_length=255)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_logs",
                        to="api.flowexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(fields=["user", "-updated_at"], name="api_flow_user_id_ceaffe_idx"),
        ),
        migrations.AddIndex(
            model_name="flowexecution",
            index=models.Index(
                fields=["flow", "-start_time"], name="api_flowexe_flow_id_3b9fc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowexecution",
            index=models.Index(
                fields=["user", "-start_time"], name="api_flowexe_user_id_cfaf6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowexecution",
            index=models.Index(
                fields=["status", "-start_time"], name="api_flowexe_status_76d346_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeexecutionlog",
            index=models.Index(
                fields=["execution", "start_time"], name="api_nodeexe_executi_197459_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeexecutionlog",
            index=models.Index(fields=["node_id", "status"], name="api_nodeexe_node_id_322ac4_idx"),
        ),
    ]
