# Generated by Django 5.2.8 on 2025-12-17 00:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_flow_flowexecution_flowtemplate_nodeexecutionlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("input", "Input"), ("llm", "LLM"), ("output", "Output")],
                        max_length=50,
                    ),
                ),
                ("icon", models.CharField(default="circle", max_length=50)),
                ("color", models.CharField(default="blue", max_length=20)),
                ("default_config", models.JSONField(default=dict)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("input_output", "Input/Output"),
                            ("processing", "Processing"),
                            ("logic", "Logic"),
                            ("integration", "Integration"),
                        ],
                        default="processing",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "display_order", "name"],
            },
        ),
    ]
