# Generated by Django 5.2.8 on 2025-12-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_nodetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
