# Generated by Django 5.2.8 on 2025-12-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_flow_celery_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="celery_task_id",
        ),
        migrations.AddField(
            model_name="flowexecution",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
