# Generated by Django 5.2.8 on 2025-12-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_remove_flow_celery_task_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodetemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("input", "Input"),
                    ("llm", "LLM"),
                    ("output", "Output"),
                    ("image_gen", "Image Generation"),
                    ("image_output", "Image Output"),
                ],
                max_length=50,
            ),
        ),
    ]
