# Generated by Django 5.2.8 on 2025-12-20 05:00

import api.features.flows.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_alter_nodetemplate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowGeneratedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("node_id", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        upload_to=api.features.flows.models.flow_generated_image_upload_to
                    ),
                ),
                ("prompt", models.TextField()),
                ("model_used", models.CharField(max_length=350)),
                ("aspect_ratio", models.CharField(blank=True, max_length=10, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_images",
                        to="api.flowexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
