# Generated by Django 5.2.8 on 2025-12-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_flowgeneratedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="default_aux_model_provider",
            field=models.TextField(blank=True, null=True),
        ),
    ]
