# Generated by Django 5.2.8 on 2025-12-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_profile_default_aux_model_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="airesponse",
            name="is_structured_output",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(
                fields=["is_structured_output"], name="api_airespo_is_stru_7ac083_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(
                fields=["provider", "is_structured_output"], name="api_airespo_provide_a1dc6e_idx"
            ),
        ),
    ]
