# Generated by Django 5.2.8 on 2026-04-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_airesponse_is_structured_output_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="daily_ai_invocations_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="daily_ai_limit",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_ai_invocation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
