/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/routes/__root";
import { Route as ProtectedRouteImport } from "./app/routes/_protected";
import { Route as AuthRouteImport } from "./app/routes/_auth";
import { Route as ProtectedIndexRouteImport } from "./app/routes/_protected/index";
import { Route as ProtectedProfileRouteImport } from "./app/routes/_protected/profile";
import { Route as ProtectedPersonasRouteImport } from "./app/routes/_protected/personas";
import { Route as ProtectedAboutRouteImport } from "./app/routes/_protected/about";
import { Route as AuthRegisterRouteImport } from "./app/routes/_auth/register";
import { Route as AuthLoginRouteImport } from "./app/routes/_auth/login";
import { Route as ProtectedFlowsIndexRouteImport } from "./app/routes/_protected/flows/index";
import { Route as ProtectedFlowsFlowIdIndexRouteImport } from "./app/routes/_protected/flows/$flowId/index";
import { Route as ProtectedFlowsFlowIdExecutionsRouteImport } from "./app/routes/_protected/flows/$flowId/executions";
import { Route as ProtectedFlowsFlowIdExecutionsExecutionIdRouteImport } from "./app/routes/_protected/flows/$flowId/executions_.$executionId";

const ProtectedRoute = ProtectedRouteImport.update({
  id: "/_protected",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedPersonasRoute = ProtectedPersonasRouteImport.update({
  id: "/personas",
  path: "/personas",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedAboutRoute = ProtectedAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => ProtectedRoute,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any);
const ProtectedFlowsIndexRoute = ProtectedFlowsIndexRouteImport.update({
  id: "/flows/",
  path: "/flows/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedFlowsFlowIdIndexRoute =
  ProtectedFlowsFlowIdIndexRouteImport.update({
    id: "/flows/$flowId/",
    path: "/flows/$flowId/",
    getParentRoute: () => ProtectedRoute,
  } as any);
const ProtectedFlowsFlowIdExecutionsRoute =
  ProtectedFlowsFlowIdExecutionsRouteImport.update({
    id: "/flows/$flowId/executions",
    path: "/flows/$flowId/executions",
    getParentRoute: () => ProtectedRoute,
  } as any);
const ProtectedFlowsFlowIdExecutionsExecutionIdRoute =
  ProtectedFlowsFlowIdExecutionsExecutionIdRouteImport.update({
    id: "/flows/$flowId/executions_/$executionId",
    path: "/flows/$flowId/executions/$executionId",
    getParentRoute: () => ProtectedRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/login": typeof AuthLoginRoute;
  "/register": typeof AuthRegisterRoute;
  "/about": typeof ProtectedAboutRoute;
  "/personas": typeof ProtectedPersonasRoute;
  "/profile": typeof ProtectedProfileRoute;
  "/": typeof ProtectedIndexRoute;
  "/flows": typeof ProtectedFlowsIndexRoute;
  "/flows/$flowId/executions": typeof ProtectedFlowsFlowIdExecutionsRoute;
  "/flows/$flowId": typeof ProtectedFlowsFlowIdIndexRoute;
  "/flows/$flowId/executions/$executionId": typeof ProtectedFlowsFlowIdExecutionsExecutionIdRoute;
}
export interface FileRoutesByTo {
  "/login": typeof AuthLoginRoute;
  "/register": typeof AuthRegisterRoute;
  "/about": typeof ProtectedAboutRoute;
  "/personas": typeof ProtectedPersonasRoute;
  "/profile": typeof ProtectedProfileRoute;
  "/": typeof ProtectedIndexRoute;
  "/flows": typeof ProtectedFlowsIndexRoute;
  "/flows/$flowId/executions": typeof ProtectedFlowsFlowIdExecutionsRoute;
  "/flows/$flowId": typeof ProtectedFlowsFlowIdIndexRoute;
  "/flows/$flowId/executions/$executionId": typeof ProtectedFlowsFlowIdExecutionsExecutionIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/_protected": typeof ProtectedRouteWithChildren;
  "/_auth/login": typeof AuthLoginRoute;
  "/_auth/register": typeof AuthRegisterRoute;
  "/_protected/about": typeof ProtectedAboutRoute;
  "/_protected/personas": typeof ProtectedPersonasRoute;
  "/_protected/profile": typeof ProtectedProfileRoute;
  "/_protected/": typeof ProtectedIndexRoute;
  "/_protected/flows/": typeof ProtectedFlowsIndexRoute;
  "/_protected/flows/$flowId/executions": typeof ProtectedFlowsFlowIdExecutionsRoute;
  "/_protected/flows/$flowId/": typeof ProtectedFlowsFlowIdIndexRoute;
  "/_protected/flows/$flowId/executions_/$executionId": typeof ProtectedFlowsFlowIdExecutionsExecutionIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/login"
    | "/register"
    | "/about"
    | "/personas"
    | "/profile"
    | "/"
    | "/flows"
    | "/flows/$flowId/executions"
    | "/flows/$flowId"
    | "/flows/$flowId/executions/$executionId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/register"
    | "/about"
    | "/personas"
    | "/profile"
    | "/"
    | "/flows"
    | "/flows/$flowId/executions"
    | "/flows/$flowId"
    | "/flows/$flowId/executions/$executionId";
  id:
    | "__root__"
    | "/_auth"
    | "/_protected"
    | "/_auth/login"
    | "/_auth/register"
    | "/_protected/about"
    | "/_protected/personas"
    | "/_protected/profile"
    | "/_protected/"
    | "/_protected/flows/"
    | "/_protected/flows/$flowId/executions"
    | "/_protected/flows/$flowId/"
    | "/_protected/flows/$flowId/executions_/$executionId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  ProtectedRoute: typeof ProtectedRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_protected": {
      id: "/_protected";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_protected/": {
      id: "/_protected/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof ProtectedIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/profile": {
      id: "/_protected/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProtectedProfileRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/personas": {
      id: "/_protected/personas";
      path: "/personas";
      fullPath: "/personas";
      preLoaderRoute: typeof ProtectedPersonasRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/about": {
      id: "/_protected/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof ProtectedAboutRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_auth/register": {
      id: "/_auth/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/login": {
      id: "/_auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_protected/flows/": {
      id: "/_protected/flows/";
      path: "/flows";
      fullPath: "/flows";
      preLoaderRoute: typeof ProtectedFlowsIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/flows/$flowId/": {
      id: "/_protected/flows/$flowId/";
      path: "/flows/$flowId";
      fullPath: "/flows/$flowId";
      preLoaderRoute: typeof ProtectedFlowsFlowIdIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/flows/$flowId/executions": {
      id: "/_protected/flows/$flowId/executions";
      path: "/flows/$flowId/executions";
      fullPath: "/flows/$flowId/executions";
      preLoaderRoute: typeof ProtectedFlowsFlowIdExecutionsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/flows/$flowId/executions_/$executionId": {
      id: "/_protected/flows/$flowId/executions_/$executionId";
      path: "/flows/$flowId/executions/$executionId";
      fullPath: "/flows/$flowId/executions/$executionId";
      preLoaderRoute: typeof ProtectedFlowsFlowIdExecutionsExecutionIdRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface ProtectedRouteChildren {
  ProtectedAboutRoute: typeof ProtectedAboutRoute;
  ProtectedPersonasRoute: typeof ProtectedPersonasRoute;
  ProtectedProfileRoute: typeof ProtectedProfileRoute;
  ProtectedIndexRoute: typeof ProtectedIndexRoute;
  ProtectedFlowsIndexRoute: typeof ProtectedFlowsIndexRoute;
  ProtectedFlowsFlowIdExecutionsRoute: typeof ProtectedFlowsFlowIdExecutionsRoute;
  ProtectedFlowsFlowIdIndexRoute: typeof ProtectedFlowsFlowIdIndexRoute;
  ProtectedFlowsFlowIdExecutionsExecutionIdRoute: typeof ProtectedFlowsFlowIdExecutionsExecutionIdRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAboutRoute: ProtectedAboutRoute,
  ProtectedPersonasRoute: ProtectedPersonasRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedFlowsIndexRoute: ProtectedFlowsIndexRoute,
  ProtectedFlowsFlowIdExecutionsRoute: ProtectedFlowsFlowIdExecutionsRoute,
  ProtectedFlowsFlowIdIndexRoute: ProtectedFlowsFlowIdIndexRoute,
  ProtectedFlowsFlowIdExecutionsExecutionIdRoute:
    ProtectedFlowsFlowIdExecutionsExecutionIdRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
